replicaCount: 1

image:
  repository: aishwariaroy239/sample-app  # Your Docker Hub repository
  pullPolicy: Always
  tag: latest  # Make sure the tag matches the one you're pushing to Docker Hub

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: true
ingress:
  enabled: true
  host: myapp.local # Add the desired host name
  annotations: {}
  # other optional ingress configurations can go here
autoscaling:
  enabled: true  # This enables the autoscaling
  minReplicas: 1  # Minimum replicas for autoscaling
  maxReplicas: 5  # Maximum replicas for autoscaling
  targetCPUUtilizationPercentage: 80  # Target CPU utilization for scaling
  targetMemoryUtilizationPercentage: 75  # Target Memory utilization for scaling

